### ISSUE TITLE
Pinned posts from web interface are not pinned in client

### ISSUE THREAD

**Issue by camerongoble** [mastodon/mastodon-android#464] opened 2022-12-15 20:33 UTC
I pinned a post in my profile, which appears correct in the web interface. Looking via the mobile app, however, the post is buried and not marked as pinned. Profiles in the app should reflect the order arranged in the web client.

**Comment by realpixelcode** [comment] 2022-12-18 12:17
Duplicate of #29

**Closed** 2024-02-28 21:57 UTC
