### ISSUE TITLE
Double ui after app resume

### ISSUE THREAD

**Issue by pbsds** [mastodon/mastodon-android#646] opened 2023-07-17 17:08 UTC
Only one layer of ui would scroll.
I'm unable to reliably reproduce this.

![Screenshot_20230717-190654095](https://github.com/mastodon/mastodon-android/assets/140964/9e4b27a0-8916-4b73-88af-cad54a520048)

**Comment by grishka** [comment] 2023-07-17 17:09
Duplicate of #619

**Closed** 2023-07-17 17:26 UTC
