### ISSUE TITLE
Change of an already posted ALT Text for images leads to 'Record not found' on save and other unforseen behaviour.

### ISSUE THREAD

**Issue by void4main** [mastodon/mastodon-android#659] opened 2023-07-29 10:10 UTC
![Screenshot_20230729-115832271.jpg](https://github.com/mastodon/mastodon-android/assets/24960880/5ef162bc-9178-4704-970e-6201f32c9e02)

**Comment by tinsukE** [comment] 2023-08-04 12:40
I can't say much for the "unforeseen behaviour" bit, but I can definitely confirm that editing the ALT text of an image of an already existing toot/status results in an error response:
```json
{"error":"Record not found"}
```

The app is trying to use the ["Update media attachment" API](https://docs.joinmastodon.org/methods/media/#update) `PUT /api/v1/media/:id HTTP/1.1` to do this, but its documentation states that this usage is incorrect:
> Update a MediaAttachment’s parameters, **before it is attached to a status and posted**.

By comparison, this feature in Tusky works and it performs the change via an update to the whole `status` entity:

- https://github.com/tuskyapp/Tusky/blob/85b7caa887cecce3464369344f1eb64acf8162a0/app/src/main/java/com/keylesspalace/tusky/service/SendStatusService.kt#L233
- https://github.com/tuskyapp/Tusky/blob/f23c0cc634d28a64e276eaa42db188a4e3a1bf9f/app/src/main/java/com/keylesspalace/tusky/network/MastodonApi.kt#L201

It does so by updating the `media_attributes` field on the status/toot.

This was my first time dabbling on this repo's code, so I don't feel confident with fixing the issue myself, but I hope to have provided enough information for the dev who'll actually tackle this problem.

**Comment by koyuawsmbrtn** [comment] 2023-08-08 15:14
Same issue here. Kind of a deal breaker.

**Comment by sk22** [comment] 2023-08-22 07:56
probably a duplicate of #517 - i'd really appreciate if this could be implemented soon

**Closed** 2023-09-28 17:36 UTC

**Comment by grishka** [comment] 2023-09-28 17:37
(multiple instances of the profile on top of each other were fixed earlier)
