### ISSUE TITLE
Mastodon app restricts context menu items

### ISSUE THREAD

**Issue by d4f5409d** [mastodon/mastodon-android#547] opened 2023-03-19 20:51 UTC
> Hi! Thanks for the information.
I have installed and verified the Mastodon app, and it appears that the context menu items are restricted.
As a workaround, you can start DeepL from the context menu "SHARE".

_Originally posted by @sakusaku3939 in https://github.com/sakusaku3939/DeepLAndroid/issues/101#issuecomment-1334789421_

Mastodon app should not restrict context menu items. I thought this will be fixed over time, but looks like it didn't, so I had to post this issue. Sorry.

**Comment by grishka** [comment] 2023-03-19 20:53
What exactly do you mean by "restricts context menu items"?

**Comment by d4f5409d** [comment] 2023-03-19 21:04
Please check the linked issue, thankyou

**Comment by grishka** [comment] 2023-03-19 21:06
I did, it did not become any clearer for me

**Comment by d4f5409d** [comment] 2023-03-19 21:26
> I did, it did not become any clearer for me

Then I'll try to explain better: so there's a button when we select texts that can redirect to deepl's translate popup. This button is not working, because the popup does not appear, but when I click on share menu and then Deepl, it works.
https://user-images.githubusercontent.com/76624594/226210629-53b608f2-7cb6-443f-9608-5d01053a6da8.mp4

**Comment by grishka** [comment] 2023-03-19 21:31
Then this is a duplicate of #509 and was already fixed as of 1.2.0. I see that you're using a fork, so please ask its maintainer to bring it up to date with the upstream.

**Comment by d4f5409d** [comment] 2023-03-19 21:32
> Then this is a duplicate of #509 and was already fixed as of 1.2.0. I see that you're using a fork, so please ask its maintainer to bring it up to date with the upstream.

I am using v1.2.0 fork 77 and it still does exist.

**Comment by grishka** [comment] 2023-03-19 21:36
Looking at https://github.com/sakusaku3939/DeepLAndroid/blob/master/app/src/main/AndroidManifest.xml, I should probably also add `android.intent.action.TRANSLATE` to that intent list. I'm reopening this issue as a reminder to myself to do it.

**Comment by grishka** [comment] 2023-03-21 23:35
> Note, that when composing a toot, it works as intended.

The app does nothing with these context menus. It's all Android's own shenanigans ¯\\\_(ツ)_/¯

**Closed** 2023-03-21 23:39 UTC

**Comment by grishka** [comment] 2023-03-21 23:40
Okay. So. The translation worked both with and without that declaration in the manifest on my Pixel 4a. So I don't know if this fixes anything. Also that app is funny, it's so much of a web view that there's a button to download the app on top :D
