### ISSUE TITLE
Server rules screen has black text in Dark Mode

### ISSUE THREAD

**Issue by adarsh1001** [mastodon/mastodon-android#618] opened 2023-07-02 06:59 UTC
![Screenshot_20230702-122627.png](https://github.com/mastodon/mastodon-android/assets/8820038/34695452-64e5-4865-bb0d-2575b41c4dd4)

The server rules screen, which comes up during the process of joining a server, has black text in dark mode which is obviously hard to read and doesn't look right.

**Expected**
All text to be in white

**App Info**
Version: 2.0.0
Android: 13

**Comment by grishka** [comment] 2023-07-02 07:00
Duplicate of #615

**Closed by grishka** 2023-07-02 07:00 UTC

**Comment by adarsh1001** [comment] 2023-07-02 07:05
@grishka Thanks, just saw. Btw there's another screen that has this:

![Screenshot_20230702-123026.png](https://github.com/mastodon/mastodon-android/assets/8820038/eeb92c01-8105-42de-9563-255d116de30d)

This is again in the initial joining process, the server name, in this case "@geekdom.social", is in black. Should I open another issue or can it be fixed in the same one since it's small?

**Comment by grishka** [comment] 2023-07-02 07:06
It's small. I should probably scan the whole project for these kinds of issues where `textColor` isn't set on TextViews.

**Comment by adarsh1001** [comment] 2023-07-02 07:07
Another one in Login 😅

![Screenshot_20230702-123629.png](https://github.com/mastodon/mastodon-android/assets/8820038/071f6b57-ac33-45e3-af1e-021b1a596919)

**Comment by grishka** [comment] 2023-07-02 07:36
You did find all of them. The other two don't matter because they're set dynamically at runtime anyway.

![image](https://github.com/mastodon/mastodon-android/assets/1478258/e33ffb8f-aa66-4688-8d72-cb36733d2df8)
