### ISSUE TITLE
Incorrect profile picture appears 

### ISSUE THREAD

**Issue by Mncricket** [mastodon/mastodon-android#431] opened 2022-11-29 17:04 UTC
When I enter the URL of the person I would like to follow Teri_Kanefield@law-and-politics.online
The user profile picture is incorrect.
![Screenshot_20221129-083550_Mastodon~2](https://user-images.githubusercontent.com/119440336/204594725-85cc7749-e595-4929-8874-36455eb81a61.jpg)

**Comment by grishka** [comment] 2022-11-29 17:05
Duplicate of #297

**Closed by grishka** 2022-11-29 17:05 UTC
