### ISSUE TITLE
[BUG] App doesnt respect filters

### ISSUE THREAD

**Issue by davidbtc2009** [mastodon/mastodon-android#94] opened 2022-04-29 13:56 UTC
I have my settings set to only show english as that is the only language i speak. However i know that some other languages use english characters or near enough so that isnt my main problem. The app also does not appear to be respecting user defined filters either

**Comment by grishka** [comment] 2022-04-29 13:57
It should respect the word filters. Language filters are something I've never seen before?

**Comment by davidbtc2009** [comment] 2022-04-29 15:39
Account settings > preferences > other

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ajhall** [comment] 2022-04-30 10:26
I can confirm that word filters don't appear to work. I have a few hashtags filtered out with this configuration that get hidden in the web UI, but display in the app:
![Screenshot_20220430-062456](https://user-images.githubusercontent.com/1380292/166101794-9075f25f-b619-4605-931b-e2c9cb841fee.png)

**Comment by javierguerragiraldez** [comment] 2022-06-12 14:47
Exactly the same to me.  I've asked and see other people are able to filter out hashtags and keywords.  Added some filters that do work on the web interface but ignored by the app.

**Comment by waldyrious** [comment] 2022-11-08 16:20
I don't see any reference to filters in the Settings screen of the app:

![Screenshot_20221108-161546.png](https://user-images.githubusercontent.com/478237/200618150-cbe22c8a-434a-4a04-a345-93500df217b0.png)

And going to the account settings, as mentioned above, doesn't show them either (it opens a webview with only account-rekated actions like moving to a different server, changing the password, etc.)

To get to the filters I have to, from the account settings page in the webview, click the hamburger menu and then select Filters. This is completely undiscoverable and should be readily accessible from the app settings screen.

**Comment by grishka** [comment] 2022-11-08 16:31
Yes, the filters aren't shown anywhere in the UI (for now), but they are loaded and applied. If some of them don't apply the way they do in the web app, this is a bug I would need to fix.

**Comment by waldyrious** [comment] 2022-11-08 16:46
@grishka would it be worth opening a separate issue to track adding a "Filters" entry in the app's Settings screen (even if just as a link to a webview, as is the case with the "Account settings" one?)

**Comment by Reschat** [comment] 2022-11-20 10:05
The app doesn't respects filters.

Example - I have a filter for #Caturday, which the website respects, but the app ignores.

Website (filtered post hidden)
![Screenshot_20221120-105920](https://user-images.githubusercontent.com/4646140/202896113-205e0891-5d60-4efa-a438-b7ad4f854217.png)

App (filtered post not hidden)
![Screenshot_20221120-105721](https://user-images.githubusercontent.com/4646140/202896156-31630aa0-0063-4348-b973-5bb6b204b205.png)

**Comment by ajhall** [comment] 2022-11-20 14:40
https://github.com/tuskyapp/Tusky/issues/2660 Tusky fixed a similar issue recently. I wonder if it might be a similar root cause.

**Comment by grishka** [comment] 2022-11-21 09:55
Hm. I think I actually tested my filter implementation on cats, too

**Comment by grishka** [comment] 2022-11-21 09:57
> [Parse html tags out of status content before applying filters.](https://github.com/tuskyapp/Tusky/commit/9dd3a3d79b8efa9ca10275abe3042dac7223c034)

Yeah okay that makes sense. I'm testing filters against raw html, which is not the best idea.

**Comment by Gargron** [comment] 2022-11-21 10:02
Mastodon 4.0 adds `filtered` property on posts so you don't need manually regex stuff client-side anymore, you just need to confirm that expiration time has not been reached yet.

**Closed** 2022-11-21 10:10 UTC
Labels: bug

**Comment by MarkSte** [comment] 2022-12-09 04:59
Posts not being filtered in Android app. Filters work as expected on desktop web interface.

**Comment by grishka** [comment] 2022-12-09 05:03
Are you using version 1.1.4?

**Comment by MarkSte** [comment] 2022-12-09 05:06
I am using Mastodon for Android 1.1.4 (45)

**Comment by Reschat** [comment] 2022-12-09 05:10
> Are you using version 1.1.4?

I'm using 1.1.4 and filters are still not working.

![image](https://user-images.githubusercontent.com/4646140/206628532-968a2153-4e9a-428f-b54b-0a954597eb96.png)

![image](https://user-images.githubusercontent.com/4646140/206628373-6ed760bd-4bd2-4f4a-9f23-4f3d660ccb0f.png)

![image](https://user-images.githubusercontent.com/4646140/206628407-cdb60096-73f3-49a1-8a65-397a1bbfbac6.png)

**Comment by grishka** [comment] 2022-12-09 05:12
Huh, profiles? It's the first time I'm seeing this option. There was never any code in the app to apply filters to posts in profiles.

**Comment by Reschat** [comment] 2022-12-09 05:17
The option is there on the website. Should it be removed from the website?

The issue also occurs in home and timelines. This is just one example that was quick for me to find just now.

**Comment by grishka** [comment] 2022-12-09 05:19
No, it's just that this option is new and I was never told that it was introduced, and so I never added support for it on my side.

> The issue also occurs in home and timelines.

In 1.1.4?

**Comment by MarkSte** [comment] 2022-12-09 05:58
It occurs for me in Home in 1.1.4.

**Comment by Reschat** [comment] 2022-12-09 06:00
Also for me. Example:

![Screenshot_20221209-065922](https://user-images.githubusercontent.com/4646140/206634969-5a88e634-b3c4-4691-825f-daf63df975ee.png)

![Screenshot_20221209-065855](https://user-images.githubusercontent.com/4646140/206634974-a05d3ff0-6718-4f65-a191-d5ab60ef798c.png)

**Comment by sk22** [comment] 2022-12-09 13:36
> @MarkSte: It occurs for me in Home in 1.1.4.

Maybe that's related to the filters only getting updated once every hour, as per https://github.com/mastodon/mastodon-android/blob/master/mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java#L254? When removing this check (and thus updating on every app restart), filters do appear to work for me (on home) (but I don't know whether the implementation is the same; as in whether the same posts are being filtered as on Web).

…so probably, if the `filtered` field is available, client-side filtering shouldn't be done at all:

> @Gargron: Mastodon 4.0 adds `filtered` property on posts so you don't need manually regex stuff client-side anymore, you just need to confirm that expiration time has not been reached yet.

Also, the whole "Hide with a warning - Show anyway" feature is missing.
![image](https://user-images.githubusercontent.com/6217438/206714022-b62387f5-61e7-4a6a-8429-22d1ce75f41a.png)

**Comment by MarkSte** [comment] 2022-12-09 16:38
That's odd. Today, without any changes in my filters (or other settings) in 12 hours, filters are now working on both the Android app and the desktop browser version. BUT...I have the filter set to "Hide with a warning" and on Android app, filtered posts are being completely hidden. On the desktop, filtered posts are being hidden behind a warning. I'm still running Android 1.1.4 (45) and v4.0.2 on the desktop.

**Comment by grishka** [comment] 2022-12-09 16:41
Yes, the app reloads the filters periodically.

> BUT...I have the filter set to "Hide with a warning" and on Android app, filtered posts are being completely hidden.

This is a new feature in Mastodon 4.0. The code to implement this has not yet been written and the warning has not yet been designed.

**Comment by MarkSte** [comment] 2022-12-09 16:49
If I understand grishka correctly, the Android app's implementation of filters fails for the setting "Hide with a warning" but works for the setting "Hide completely." I just changed my setting to "Hide completely" and indeed the offending posts are now gone.

**Comment by saket** [comment] 2023-11-19 06:25
> Mastodon 4.0 adds `filtered` property on posts so you don't need manually regex stuff client-side anymore, you just need to confirm that expiration time has not been reached yet.

@Gargron Wouldn't this not work for old posts that have already been downloaded by clients?
