### ISSUE TITLE
Wrong thumbnail on search

### ISSUE THREAD

**Issue by da5nsy** [mastodon/mastodon-android#361] opened 2022-11-16 04:51 UTC
![Screenshot_20221115-234628](https://user-images.githubusercontent.com/3739866/202086253-cb4893f2-f5ef-4f79-ac31-a452ad517ed7.png)

![Screenshot_20221115-234633](https://user-images.githubusercontent.com/3739866/202086294-6610ebb4-ef0d-4749-9a29-5319ff435292.png)

Thumbnail image is of someone I have interacted with recently, so perhaps a cache issue?

This has happened multiple times.

Pixel 4a 5G
TP1A.221005.002
Mastodon for Android v1.1.3 (39)
Server: fosstodon.org

**Comment by grishka** [comment] 2022-11-16 04:53
Duplicate of #297 which I fixed yesterday.

**Closed by grishka** 2022-11-16 04:53 UTC

**Comment by da5nsy** [comment] 2022-11-16 04:56
Great! Thank you @grishka!
