### ISSUE TITLE
"java.lang.NumberFormatException: Expected an int but was 7985735754 at line 1 column 152890 path $[36].account.followers_count" error screen

### ISSUE THREAD

**Issue by planetjunkie** [mastodon/mastodon-android#304] opened 2022-11-06 05:35 UTC
This error keeps randomly Popping up and I don't really know the cause

![Screenshot_20221106-093426.png](https://user-images.githubusercontent.com/79197022/200155883-b2799fa6-63f9-4b45-81b9-3560d8d05f89.png)

**Comment by grishka** [comment] 2022-11-06 05:36
Duplicate of #301, already fixed

**Closed by grishka** 2022-11-06 05:36 UTC
