### ISSUE TITLE
Can't view image descriptions

### ISSUE THREAD

**Issue by githubgirly** [mastodon/mastodon-android#107] opened 2022-05-02 18:16 UTC
I know a screen reader can still read them, but it's important to me to see if there IS a description so I know if I can boost these posts to my disabled followers

**Comment by realpixelcode** [comment] 2022-05-02 22:08
I'd like to be able to view image descriptions without having to use a screen reader 🤷

**Comment by grishka** [comment] 2022-05-13 16:57
Duplicate of #100

**Closed** 2022-12-30 02:10 UTC
Labels: duplicate, feature request, ui/ux related
