### ISSUE TITLE
Feed crashes when it includes post from user with too many followers

### ISSUE THREAD

**Issue by bbliem** [mastodon/mastodon-android#303] opened 2022-11-06 00:16 UTC
I had posts by the user `@rune@mcd.dk` in my feed and their account seems to have 7.99 billion followers. Not sure if that's by some bug or a (perhaps intentionally) misbehaving server.

When I open the Mastodon Android app, instead of my feed I get an error `java.lang.NumberFormatException: Expected an int but was ...`, probably because the number of followers (7985735753) is too high. This probably happens to everyone who has that user's posts in their feed.

As a workaround, I suspended that user from my own server and the app works again. I don't know if this is the best way of dealing with the problem though.

**Comment by rossholmberg** [comment] 2022-11-06 01:44
I'm getting the same error regularly, and I don't follow anyone with anywhere near that many followers. Restarting the app generally helps, but it's coming up a lot. Here's a screenshot for the full error message. Not the numbers are not always the same.
![Screenshot_20221106-113706](https://user-images.githubusercontent.com/14091641/200150198-91a5d7a8-4c95-4a19-8529-5020c42f513b.png)

**Comment by grishka** [comment] 2022-11-06 01:55
Duplicate of #298

**Closed** 2022-11-06 02:39 UTC
