### ISSUE TITLE
Bug: Content warning blur on images is missing when navigating up from post view

### ISSUE THREAD

**Issue by schuelermine** [mastodon/mastodon-android#428] opened 2022-11-28 21:27 UTC
To reproduce:

1. Find a post with a content warning and an image
2. Tap to reveal the image
3. Tap the post to open the post view
4. Tap the hide button in the top left corner
5. Press back

**Comment by realpixelcode** [comment] 2022-11-29 07:54
Duplicate of #171

**Closed** 2022-11-29 12:19 UTC
